Get rid of engine directory

diff --git a/bin/bitter b/bin/bitter
--- a/bin/bitter
+++ b/bin/bitter
@@ -2,40 +2,75 @@
 
 VERSION=0.1.10
 
+get_script_dir () {
+  script_dir="$(dirname $(test -L "$0" && readlink "$0" || echo "$0"))"
+  echo "$script_dir"
+}
+
+configure_notes_git () {
+  git config core.bare false
+  git config core.worktree ../notes
+  git config receive.denycurrentbranch ignore
+
+  # Arrange hook for post-receive event
+  if [ ! -e hooks/post-receive ]; then
+    echo "#!/bin/sh" > hooks/post-receive
+  fi
+  if ! grep --quiet "# Bitter" hooks/post-receive; then
+    cat >> hooks/post-receive <<EOF
+
+# Bitter
+git checkout -f
+touch ../notes/reindex-needed
+EOF
+  fi
+  chmod +x hooks/post-receive
+}
+
 setup () {
-  if [ -e engine/setup.sh ]; then
-    echo "It appears you already have set up."
+  if [ -e notes.git/HEAD ]; then
+    echo "notes.git exists.\nIt appears you already have set up."
     exit 1
   fi
 
-  which_dir="$(dirname $(which $0))"
-  link_dir="$(dirname $(test -L "$0" && readlink "$0" || echo "$0"))"
-  script_dir=$(cd $which_dir/$link_dir; pwd -P)
+  script_dir=$( get_script_dir )
 
-  mkdir engine
-  cp $script_dir/../setup.sh engine/
-  cp $script_dir/../server.js engine/
-  cp -R $script_dir/../default engine/
-  ln -s $script_dir/../node_modules engine/
+  echo "setting up..."
 
-  cd engine
-  ./setup.sh
+  mkdir notes notes.git
+
+  # Prepare notes.git
+  cd notes.git
+  git --bare init
+  configure_notes_git
+
+  # Copy default files
+  cd ..  # basedir
+  cp -R $script_dir/../default/. notes/
+
+  # Commit them
+  cd notes.git
+  git add .
+  git commit -m "Setup"
+
+  echo "\nsetup completed"
 }
 
 server () {
-  if [ -e engine/server.js ]; then
-    node engine/server.js
-  else
-    echo "Can't find engine/server.js."
-    echo "Do this command from the directory you have set up."
-    echo "If you have not set up, do \"bitter setup\" first."
+  if [ ! -e notes.git/HEAD ]; then
+    echo "Can't find notes.git"
+    echo "Execute this command from the directory that contains notes.git."
+    echo "If you have not set up yet, do \"bitter setup\" first."
     exit 1
   fi
+
+  script_dir=$( get_script_dir )
+  node $script_dir/../server.js
 }
 
 gitconfig () {
   if [ ! -e HEAD ]; then
-    echo "Do this command in bare .git directory"
+    echo "Execute this command in bare .git directory"
     exit 1
   fi
 
@@ -53,27 +88,8 @@ gitconfig () {
   fi
   mkdir ../notes
   echo "created ../notes for worktree"
-
-  git config core.bare false
-  git config core.worktree ../notes
-  git config receive.denycurrentbranch ignore
-
-  # Arrange hook for post-receive event
-  if [ ! -e hooks/post-receive ]; then
-    echo "#!/bin/sh" > hooks/post-receive
-  fi
-  if ! grep --quiet "# Bitter" hooks/post-receive; then
-    cat >> hooks/post-receive <<EOF
-
-# Bitter
-git checkout -f
-touch ../engine/reindex-needed
-EOF
-  fi
-  chmod +x hooks/post-receive
-
+  configure_notes_git
   git checkout -f
-
   echo "successfully configured"
 }
 
